name: urovo_scanner
description: "Projeto elaborado para leitor urovo"
version: 1.0.0
repository: https://github.com/andrejp09/urovo_scanner

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: br.com.bongiolo.urovo_scanner
        pluginClass: UrovoScannerPlugin
